"""create stocks, metrics, and events tables

Revision ID: 816437e392f6
Revises: 60ea883f3d82
Create Date: 2026-04-28 10:23:43.136248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '816437e392f6'
down_revision: Union[str, Sequence[str], None] = '60ea883f3d82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('ticker_symbol', sa.String(length=5), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('date_refreshed', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_symbol')
    )
    op.create_table('events',
    sa.Column('ex_dividend_date', sa.Date(), nullable=False),
    sa.Column('payout_date', sa.Date(), nullable=False),
    sa.Column('cash_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pct_change', sa.Float(), nullable=True),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_stock_id'), 'events', ['stock_id'], unique=False)
    op.create_table('metrics',
    sa.Column('yield_', sa.Float(), nullable=False),
    sa.Column('payout_ratio', sa.Float(), nullable=False),
    sa.Column('frequency', sa.String(length=10), nullable=False),
    sa.Column('annual_dividend', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('next_ex_dividend_date', sa.Date(), nullable=False),
    sa.Column('next_payout_date', sa.Date(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metrics')
    op.drop_index(op.f('ix_events_stock_id'), table_name='events')
    op.drop_table('events')
    op.drop_table('stocks')
    # ### end Alembic commands ###
