"""add unique constraint on events table
Revision ID: cb7c6c3f2302
Revises: 816437e392f6
Create Date: 2026-04-28 11:55:47.128984
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cb7c6c3f2302"
down_revision: Union[str, Sequence[str], None] = "816437e392f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "uq_event_stock_date", ["stock_id", "ex_dividend_date"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_constraint("uq_event_stock_date", type_="unique")
    # ### end Alembic commands ###
